### ISSUE TITLE
ReorderHead transformer accidentally deduplicates based on URL

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox-php#125]
The `ReorderHead` transformer uses the URL as an array key when collecting `<script>` elements to reorder. This means that if multiple `<script>` elements use the same URL (like for `.mjs` script + `nomodule` fallback), they overwrite each other in the array and are effectively "deduplicated".

The `ReorderHead` transformer needs a more robust algorithm. It seems that deduplication is still desirable, but will need to rely on "URL + a selection of attributes". The exact selection needs to be clarified, but for now it might help to hash the URL + the presence of `nomodule` as a first bug fix.

**Comment by schlessera** [comment]
Here's what the Go Optimizer is using: https://github.com/ampproject/amppackager/commit/8e2622daa536d5d49dbb6c80f39cbffe65053f72#diff-4e49b75e7da4b38f1a1be19bfc9c6b9e12dbe964eda574cf83ee419776c782f0R80-R94

**Comment by westonruter** [comment]
> This means that if multiple `<script>` elements use the same URL (like for `.mjs` script + `nomodule` fallback), they overwrite each other in the array and are effectively "deduplicated".

How would they use the same URL? The module scripts end in `.mjs` and the nomodule ones end in `.js`. The problem seems to rather be the reliance on the `custom-element` and `custom-template` attributes. Switching this to use `src` as per https://github.com/ampproject/amp-toolbox/pull/1192 seems to do it.

**Comment by schlessera** [comment]
Fixed via #130
