### ISSUE TITLE
PHPCS fails to match files when developing on package installed as vendor dependency

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-toolbox-php#132]
In regards to https://github.com/ampproject/amp-toolbox-php/pull/130#discussion_r608739757, I found that when I try developing with `amp-toolbox-php` when it is installed as a vendor dependency in the AMP plugin, the `phpcs`/`phpcbf` commands find no files. 

The reason appears to be that the path is `.../amp/vendor/ampproject/amp-toolbox` which contains `vendor/` so it is matched in this `exclude-pattern`:

https://github.com/ampproject/amp-toolbox-php/blob/bda7ad4d0585c426dc72145aff52a17aab456689/.phpcs.xml.dist#L13-L14

I found that I needed to change it to:

```xml
	<exclude-pattern>amp-toolbox/vendor/</exclude-pattern>
	<exclude-pattern>amp-toolbox-php/vendor/</exclude-pattern>
```

The first one prevents matching against itself when installed as a Composer vendor dependency, and the second one is needed when the repo is cloned separately such as when GitHub actions are run.

**Comment by schlessera** [comment]
The second one only works correctly if you stick to the repo name being the directory in which the source is located. If you rename the directory to something else (like for example `amp-toolbox-php-backup`), it will not work anymore...
