### ISSUE TITLE
Evaluate improved lazy-loading behavior for hero images

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox-php#147]
The following scenarios should be tested to evaluate improved lazy-loading behavior with regards to optimizing hero images:

1. Remove lazy-loading not only for images marked with `data-hero`, but also those marked with `data-hero-candidate`. See https://github.com/ampproject/amp-toolbox-php/pull/141#discussion_r610916394
2. For images not marked with `data-hero`, check if there is a `noscript > img` to copy an existing `loading` attribute from. See https://github.com/ampproject/amp-toolbox-php/pull/141/files#r611001917

**Comment by westonruter** [comment]
> 2\. For images not marked with `data-hero`, check if there is a `noscript > img` to copy an existing `loading` attribute from.

This seems to work well. I'll open a PR later today.
