### ISSUE TITLE
Remove preload for AMP runtime again when boilerplate was removed

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox-php#17]
## Feature description

When the AMP boilerplate is removed by the SSR logic, preloading of the AMP runtime is less critical and it seems to slow down other assets that are of higher priority in that scenario.

The Optimizer should remove an existing preload for the AMP runtime again when the boilerplate was indeed removed.

This was originally reported by @mehigh for an [XWP](https://xwp.co/) project.

/cc @sebastianbenz

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* Add small transformer that runs after the `ServerSideRendering` transformer and removes an existing AMP runtime preload iff the AMP boilerplate was removed.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
Given that the test results all seem to indicate this to be a net positive change, I'd like to implement this for the PHP Optimizer. @sebastianbenz, @kristoferbaxter should I also open corresponding issues for the Go and JS versions of the Optimizer?

**Comment by kristoferbaxter** [comment]
We can run a more thorough experiment before moving forward.

Will sync with team today on this.

**Comment by sebastianbenz** [comment]
Are there any updates on this?

**Comment by jridgewell** [comment]
Maybe @kevinkimball or @erwinmombay can run an AMP Cache experiment for this? Should be simple enough.

**Comment by schlessera** [comment]
@sebastianbenz @kristoferbaxter @jridgewell Any updates on this? It's looking like a promising change, so I'd love to implement this for the library and WordPress integration.

**Comment by westonruter** [comment]
I've prototype this along with postponing the loading of scripts that aren't render-critical at https://github.com/ampproject/amp-wp/issues/6182#issuecomment-865363567.

**Comment by kristoferbaxter** [comment]
There is no update beyond the need for statistical analysis at a large enough scale to validate results.

If we choose to adopt this and other suggestions there are several changes required for systems that ingest AMP documents and validate them.

**Comment by kristoferbaxter** [comment]
We should move forward with removal for now, data suggests the origin performance can be better without, but the preload version from a cache will continue to insert and perform better with in that scenario.

**Comment by robin-scott** [comment]
@westonruter found link to this from here https://wordpress.org/support/topic/preload-amp-runtime-2/#:~:text=1%20month%2C%204%20weeks%20ago - the issue which users face running AMP plugin is they get dings saying to add the preload here:

https://amp.dev/page-experience/

Unless the test itself is updated not to prompt users on this, we're looping everyone back to then tell them to ignore it.

**Comment by westonruter** [comment]
@robin-scott The issue to fix this is https://github.com/ampproject/amp-toolbox/issues/1256
