### ISSUE TITLE
New 0.5 release dont pass amp validator

### ISSUE THREAD

**Issue by chakib32** [ampproject/amp-toolbox-php#178]
The 0.5.0 release is not passing amp validator.  [This page for exemple](https://horaire-priere.be/heure-priere-bruxelles-89-be)
![amp error](https://user-images.githubusercontent.com/54911703/116873778-870e8380-ac18-11eb-937f-93701f5dad06.JPG)

**Comment by schlessera** [comment]
@chakib32 The above validation errors look like you passed a non-AMP page into the validator.

When I try to validate the URL you've provided, it passes validation for me:
![Image 2021-05-03 at 1 43 53 PM](https://user-images.githubusercontent.com/83631/116877358-bec7fc00-ac15-11eb-8453-98b46434d1ea.jpeg)

**Comment by chakib32** [comment]
I'm testing with the ampproject validator : https://validator.ampproject.org/

**Comment by westonruter** [comment]
@chakib32 It appears that CloudFlare is adding a DDoS human check screen which is causing this. I put your page through the AMP Validator and I can see it fail with that:

![image](https://user-images.githubusercontent.com/134745/116909632-59661200-abf9-11eb-85e1-abbb8251a10d.png)

This is the page that CloudFlare is serving back:

> ![image](https://user-images.githubusercontent.com/134745/116909702-700c6900-abf9-11eb-9897-189f7a55dfac.png)

So it's not a problem with amp-toolbox-php, but rather with the CloudFlare configuration.
