### ISSUE TITLE
Server-side rendering can cause style[amp-custom] CSS overage

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-toolbox-php#19]
## Bug Description

Given an AMP page that has an `style[amp-custom]` which is just under the 75000 byte limit at 74,998 bytes. 

If this AMP page also has an `amp-analytics` tag, then the SSR transformer will end up adding an inline `style` to this element like so:

```html
<amp-analytics type="analytics" class="i-amphtml-layout-fixed i-amphtml-layout-size-defined" style="width:1px;height:1px;" i-amphtml-layout="fixed">
```

The result is an AMP validation error is leaked to the frontend:

> The author stylesheet specified in tag ‘style amp-custom’ and the combined inline styles is too large – document contains 75023 bytes whereas the limit is 75000 bytes.

Why is this? It's because `width:1px;height:1px;` (21 bytes) is _added_ to the size of `style[amp-custom]` (74,998 bytes): 74,998 + 21 = 75,023. The key line in the error message is “and the combined inline styles”.

Originally reported in support topic: https://wordpress.org/support/topic/gcs-error/

Example document that has this problem: https://gist.github.com/westonruter/4dd1f81cc393568e9eef3e008f6615e6#file-que-son-gadget-amp-html

The current workaround is to install the [AMP Disable SSR](https://gist.github.com/westonruter/8d52c0b807e6dfbbdf2219622d0f4a7e) plugin.

## Expected Behaviour

SSR should not cause the total `amp-custom` CSS to go over 75000 bytes. It should keep track of how much CSS it is adding to the page, and if that causes the total to go over what is already in `style[amp-custom]`, it should abort SSR.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
The draft PR https://github.com/ampproject/amp-wp/pull/5521 needs to be moved over to this repository.
