### ISSUE TITLE
Extend Optimizer with transformer for module/nomodule scripts (ESM)

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-toolbox-php#20]
## Feature description

See https://github.com/ampproject/amp-toolbox/pull/722.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by schlessera** [comment]
The draft PR https://github.com/ampproject/amp-wp/pull/5078 needs to be transferred over to this repository.

**Comment by kristoferbaxter** [comment]
Please note that the AMP Performance WG does not yet recommend the usage of `modulepreload`, but instead uses a correctly configured `preload` for the Google AMP Cache.

Would prefer this change does not use `modulepreload` and mirrors the functionality on the Google AMP Cache when module mode is enabled.

**Comment by westonruter** [comment]
> Please note that the AMP Performance WG does not yet recommend the usage of `modulepreload`, but instead uses a correctly configured `preload` for the Google AMP Cache.

Note that `modulepreload` has been implemented as of https://github.com/ampproject/amp-toolbox/pull/1161, but apparently only temporarily so.

**Comment by westonruter** [comment]
@sebastianbenz Should we be going live in WP with `preload` or `modulepreload`?

**Comment by kristoferbaxter** [comment]
There was a recent regression in preload when used with module scripts in Chromium.

Engineers on the V8 team are working to address, and as a temporary measure we've elected to use modulepreload on the Google AMP Cache. This carries a downside, as Safari will not process these directives.

Until this is resolved, modulepreload is the best of the bad options.
