### ISSUE TITLE
Preload Hero images doesn't work after \ServerSideRendering

### ISSUE THREAD

**Issue by 06romix** [ampproject/amp-toolbox-php#204]
If used default sequence of transformers ServerSideRendering would move media attributes to custom CSS before Optimizer preload hero images.

Media attribute is removed in [`Transformer\ServerSideRendering::adaptBlockingAttributes()`](https://github.com/ampproject/amp-toolbox-php/blob/8d28ed152416fd162e07b54ade1c0cc7df94bbe2/src/Optimizer/Transformer/ServerSideRendering.php#L750-L825)
And here we have check [`Transformer\PreloadHeroImage::generatePreload()`](https://github.com/ampproject/amp-toolbox-php/blob/6eee28fe4efb49d155ec189710ef15fb59b28f63/src/Optimizer/Transformer/PreloadHeroImage.php#L499-L609)

Should transformers have a different sequence?

**Comment by westonruter** [comment]
It seems you're right. The `PreloadHeroImage` transformer is coming _after_ `ServerSideRendering`:

https://github.com/ampproject/amp-toolbox-php/blob/6eee28fe4efb49d155ec189710ef15fb59b28f63/src/Optimizer/Configuration.php#L45-L55

**Comment by schlessera** [comment]
Yes, indeed, we need to move `PreloadHeroImage` before `ServerSideRendering`.

I'm wondering if we also should have a lightweight mechanism to check ordering and throw warnings if inter-dependencies are not met, as people can freely re-arrange the transformers...

**Comment by 06romix** [comment]
I've created request #209 for a fast fix and going to make order checking.

**Comment by schlessera** [comment]
First issue fixed via #209 and second issue superseded by #219.
