### ISSUE TITLE
Escape slashes in regexes at spec generation time for sake of delimiters in `preg_match()` at runtime

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-toolbox-php#238]
As mentioned in https://github.com/ampproject/amp-toolbox-php/pull/221#discussion_r646991471, since the spec regexes will be sent to `preg_match()`, we should escape the `/` to not conflict with the delimiter. See https://github.com/ampproject/amp-wp/pull/6303/commits/afd117289ee863011cb1a7dc4e096b49bd4a5f15. Some regexes in the spec already escape `/` but not all.

**Comment by schlessera** [comment]
I recommend not adding "arbitrary" escaping, and rather let the consuming code decide how to deal with escaping. I suggest using the `chr(1)` character as delimiter in the consuming code.
See https://github.com/ampproject/amp-toolbox-php/pull/221#discussion_r650663616
