### ISSUE TITLE
Detect malformed byte sequences and warn the user

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox-php#24]
The `Dom\Document` abstraction relies on valid byte sequences to either keep existing UTF-8 content or convert content in a different encoding to the UTF-8 encoding.

If a document contains a malformed byte sequence, the parsing done by `DOMDocument` fails in a random way (silently) and produces garbage:
![image](https://user-images.githubusercontent.com/83631/98935201-768c1480-24e3-11eb-9765-c174ae3ff3dd.png)

This is not only bad because of the garbled end result, it also looks like the AMP conversion is the culprit and makes it difficult for the user to diagnose the real issue.

The source of this problem (the malformed byte sequence) can actually be detected in the non-AMP document and is also shown by the W3C validator:
![Showing results for __news androidlist jp_2020_11_12__E3_81_99_E3_81_  2020-11-12 at 11 58 47 AM](https://user-images.githubusercontent.com/83631/98935291-9a4f5a80-24e3-11eb-96f3-45360b7d1eee.png)

PHP has a function `mb_check_encoding()` which seems to be able to detect malformed byte sequences (see https://3v4l.org/ciAPf). We should investigate whether we can detect this problem upfront and warn the user about it.

Things to check:
- How reliable does `mb_check_encoding()` work, and does it get trigger on other issues as well?
- What is the performance impact of checking the entire document before parsing it via `Dom\Document`?

**Comment by westonruter** [comment]
Was the issue caused by truncating text via `substr()` instead of `mb_substr()`?

**Comment by schlessera** [comment]
I assume so. The user didn't get back to me on what the actual code was that broke the encoding, but `substr` is the most likely culprit.

**Comment by 06romix** [comment]
> How reliable does mb_check_encoding() work, and does it get trigger on other issues as well?

On PHP documentation there is [the user note](https://www.php.net/manual/en/function.mb-check-encoding.php#89286) with test detecting bad byte stream and bad byte sequence. But now I mb_check_encoding works correctly on different PHP versions. So I think `mb_check_encoding` can detect both bad byte stream and bad byte sequence.

> What is the performance impact of checking the entire document before parsing it via Dom\Document?

I added `mb_check_encoding` to `\AmpProject\Dom\Document::loadHTML` and parse html took 10% more time.
Tested 10 times with 10000 parsings using `tests/spec/valid-amp/files/amp-selector.html`

**Comment by schlessera** [comment]
> I added mb_check_encoding to \AmpProject\Dom\Document::loadHTML and parse html took 10% more time.

Hmm, that's quite a big hit for something not a lot of people will actually need.

I'm wondering now whether we should add a general option to the optimizer to optimize execution time at the expense of safeguards.

@westonruter Thoughts?

**Comment by westonruter** [comment]
Yeah, if it causes an additional 10% of execution time, then I'd say it should be disabled by default. It can be enabled via a configuration option to debug mojibake issues.

**Comment by schlessera** [comment]
Fixed via #200
