### ISSUE TITLE
Missing JavaScript minifier

### ISSUE THREAD

**Issue by ediamin** [ampproject/amp-toolbox-php#260]
In order to minify HTML in PHP we need a PHP library that minifies JavaScript as well. We need to find a suitable PHP library and add that to our code.

Related to https://github.com/ampproject/amp-toolbox-php/issues/14

**Comment by swissspidy** [comment]
I've used https://github.com/mck89/peast in the past to parse JS. Example formatting: https://github.com/mck89/peast/blob/master/doc/rendering.md#compact

**Comment by schlessera** [comment]
Using peast is a good idea! While having the code in the AST form, we could also safely make other modifications that might be needed, like renaming variables or so.

I'd just make peast an optional dependency then and enable modification of script when peast's presence is detected.
