### ISSUE TITLE
Undefined property: `Document::documentElement`

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-toolbox-php#27]
In the Web Stories plugin we parse the story markup using `Document::fromHtml( $markup, get_bloginfo( 'charset' ) )` for further processing.

A user has now reported an issue with that, where somehow the parsing fails, causing the `doccumentElement` property to be `null`. Here's the screenshot of the error:

<img width="937" alt="Screen Shot 2020-11-12 at 1 35 18 PM" src="https://user-images.githubusercontent.com/841956/98996090-9c8cd580-2532-11eb-8771-6a6c4402b997.png">

My hunch is that it's related to an encoding issue, but not sure.

Maybe it's possible  to add some hardening to the `Document` class around instances of using `$this->documentElement`, i.e. first checking whether it exists

**Comment by westonruter** [comment]
This has come up before. It's usually an issue with the `dom` extension being misconfigured:

* https://wordpress.org/support/topic/i-cant-access-my-amp-pages/#post-12580773
* https://wordpress.org/support/topic/i-have-a-internal-server-error/

**Comment by swissspidy** [comment]
Interestingly, when I told the user to try activating the AMP plugin as a workaround (because the web Stories plugin will short-circuit), it just worked! Since the plugin essentially uses the same class under the hood, it perhaps indeed is an encoding issue?

Maybe we shouldn't be passing `get_bloginfo( 'charset' )` in Web Stories (which seems odd in retrospect) and just let the class figure out the encoding.

**Comment by westonruter** [comment]
That _is_ interesting. 

I can see that Web Stories is indeed passing the `charset`:

https://github.com/google/web-stories-wp/blob/8ff6b46cb0accf4229cc095e115b22e45f485c31/includes/Story_Renderer/HTML.php#L90

Whereas in the AMP plugin we do not pass anything (which results in `auto`):

https://github.com/ampproject/amp-wp/blob/97e2011df939fcca9448895a92c9480bfc817f25/includes/class-amp-theme-support.php#L2022

When nothing is passed, then it's important for there to be a `meta[charset]` present to indicate the encoding is properly identified by libxml, I think.

**Comment by swissspidy** [comment]
> When nothing is passed, then it's important for there to be a `meta[charset]` present to indicate the encoding is properly identified by libxml, I think.

This is always present in our case, so should be safe there. Opened https://github.com/google/web-stories-wp/issues/5286 to address this.

I'll leave this ticket open to discuss potential hardening in this class nonetheless.

**Comment by schlessera** [comment]
I'll add hardening to avoid the fatal error. But it would be interesting to know what `get_bloginfo( 'charset' )` actually returns in the cases where this breaks...

**Comment by swissspidy** [comment]
If I'll find out I'll let you know for sure 👍
