### ISSUE TITLE
Specific anchor tags in inline scripts breaks the script when optimized

### ISSUE THREAD

**Issue by safalshrestha** [ampproject/amp-toolbox-php#306]
Hi, 

We have a site which still uses AMP functionality but is not AMP cached anymore. The website had a very high LCP so we were trying to optimize it using AMP optimizer. We got a good result trying the node optimizer so implementing the php one now.

Everything works apart from a long inline script we have in the head tag. This script is getting closed mid way by AMP Optimizer. 

I tried using custom configuration thinking it would be one of Transformer causing this but no luck. Even with just 
`Transformer\RewriteAmpUrls::class,`

I still have the issue.

Would be have any configuration to disable this? I can try to post a sample JS if required.

Thanks very much.

**Comment by schlessera** [comment]
Hi @safalshrestha,
If no transformer is causing this, than you might be hitting a bug with PHP's `DOMDocument` or `libxml` implementation.
To fix this, we'll need the JS that is breaking so we can replicate the problem.

**Comment by safalshrestha** [comment]
Hi @schlessera thanks very much for the reply.

While I was about to prepare the JS, I came to realise it might be the anchor tags,  `>>variable<<`,  we have in our script causing the issue.

Below is the raw sample code and optimized code:

Raw code
```
<script>
    let p = {
        q: 'https://test-url.com',
        r: true,
        s: "u",
        t: "v",
        y: "https://w.com",
        z: "https://x.com",
        aa: "bb",
        cc: dd,
        ee: "",
        ff: true,
        gg: false,
        hh: false,
        ii: false,
        jj: 'Welcome!',
        kk: 'Unable to process payment. Please try again',
        ll: "<div class='fp-orig-price'><span class='fp-strikethrough'><span class='fp-pricing-org-price-currency'> >>original_price_currency<< </span><span> >>original_price_amount<< </span></span></div>",
        mm: '<li class=">>enabled<<">>>description<<</li>',
        nn: "<p class='ep17payment1-action'><div id='fp-ap-wrap' class='-ta:c'></div></p>",
        ss: "",
        tt: "<div></div>",
    };

</script>
```


Optimized html:
```
<script>
--
  | let p = {
  | q: 'https://test-url.com',
  | r: true,
  | s: "u",
  | t: "v",
  | y: "https://w.com",
  | z: "https://x.com",
  | aa: "bb",
  | cc: dd,
  | ee: "",
  | ff: true,
  | gg: false,
  | hh: false,
  | ii: false,
  | jj: 'Welcome!',
  | kk: 'Unable to process payment. Please try again',
  | ll: "<div class='fp-orig-price'><span class='fp-strikethrough'><span class='fp-pricing-org-price-currency'> >>original_price_currency<< <span> >>original_price_amount<<",
  | mm: '<li class=">>enabled<<">>>description<<',
  | nn: "<p class='ep17payment1-action'><div id='fp-ap-wrap' class='-ta:c'></script></p>",
  | oo: "<p class="ep17payment1-action"></p><div id="fp-gp-wrapper" class="-ta:c"><button type="submit" class="button1 -mw1"><span><span>Submit</span> App</span></button><div id="fp-gp-wrap" style="opacity: 0 !important;"></div></div>",
  | pp: "<h4 class="-t:0">Other methods</h4><div class="ep17payment1-wrap">&gt;&gt;other_type",
  | qq: "<p class="ep17payment1-action"><button class="ep17button2 cx-a" id="fp-card-&gt;&gt;id&lt;&lt;" data_id="&gt;&gt;id&lt;&lt;"><span>&gt;&gt;description</span></button></p>",
  | ss: "",
  | tt: "<div></div>",
  | };

```
The code seems to break just at variable **ll** closing script at **nn**

Would there be a way to avoid such scenario?

Appreciate your help. Thanks very much.

**Comment by safalshrestha** [comment]
Hi @schlessera 

Just an update to this:

Tried using the regex way of replacing anchors and adding them back after optimization as mentioned here: 
https://github.com/ampproject/amp-toolbox-php/issues/202

https://github.com/contao/core-bundle/issues/1360

However that didn't work either. It still fails on **ll** and closes the script after nn. :( 

```
ll: "<div class='fp-orig-price'><span class='fp-strikethrough'><span class='fp-pricing-org-price-currency'> ---fpanchor-placeholder---6116533ed2ad51.16253801 <span> ---fpanchor-placeholder---6116533ed2ae17.12340776 ",
mm: '<li class="---fpanchor-placeholder---6116533ed2ae35.44476527"> ---fpanchor-placeholder---6116533ed2ae55.96172060 ',
nn: "<p class='ep17payment1-action'><div id='fp-apple-pay' class='-ta:c'></script></p>",

```

**Comment by ediamin** [comment]
Hi, @safalshrestha As @schlessera guessed, it is indeed a problem related to the core PHP `DOMDocument` class. It removes any closing tag that could be found in an inline script variable. I've [raised a PR](https://github.com/ampproject/amp-toolbox-php/pull/322) to fix this issue hopefully that will solve the problem.

**Comment by safalshrestha** [comment]
Thanks @ediamin @schlessera Appreciate it! :+1:
