### ISSUE TITLE
Composer unable to install `bin/amp` binary as it does not exist in dist archive

### ISSUE THREAD

**Issue by pierlon** [ampproject/amp-toolbox-php#308]
When requiring this package Composer emits the warning:

> Skipped installation of bin bin/amp for package ampproject/amp-toolbox: file not found in package

That's because the `bin` directory is not included when building the dist archive:

https://github.com/ampproject/amp-toolbox-php/blob/0baeb7155c3ffaef02688eb2d2134328f2258762/.gitattributes#L11

I think the simplest solution here is to remove the `bin` property from the composer.json file, but I may be wrong 🤷.

**Comment by schlessera** [comment]
The `bin/amp` should still be linked by Composer. We need to adapt the `.gitattributes` file instead. It should not exclude the whole of the `bin` folder, but rather, the parts that are used for development only.

Right now, the `bin/amp` file is the only thing that is needed, so the rules should be something like:
```
/bin/*.php    export-ignore
/bin/*.bash   export-ignore
/bin/src      export-ignore
```
