### ISSUE TITLE
numberFormatting in responsiveSizer

### ISSUE THREAD

**Issue by SimonKraus** [ampproject/amp-toolbox-php#37]
I encountered an problem in optimizeHtml while in an de_DE.UTF-8 environment. 
The i-amphtml-sizer's padding-top is set with comma instead of dot leading to non-rendered images.

please consiger using
        $paddingString = (string) number_format($padding, 4, '.');
instead of 
        $paddingString = (string) round($padding, 4);
in ServerSideRendering::createResponsiveSizer

**Comment by schlessera** [comment]
Indeed, `round()` is affected by the locale. Good catch!

Are you interested in providing a PR for this?

**Comment by SimonKraus** [comment]
#38 

done so. 

have had some serious debugging done to figure out why images were rendered in my local env but didn't appear in staging system. wasn't the place where i expected the behaviour to come from ;)
