### ISSUE TITLE
Error when using AutoExtensions transformer

### ISSUE THREAD

**Issue by saywo** [ampproject/amp-toolbox-php#503]
![SS 2022-02-25 19 45 40](https://user-images.githubusercontent.com/44390371/155702295-efb48be9-462f-4453-9048-ec2e2e5a81a2.jpg)

```
 $configurationData = [
        Configuration::KEY_TRANSFORMERS => [
          AutoExtensions::class,
          ServerSideRendering::class,
          TransformedIdentifier::class,
        ],
      ];
```

When I added AutoExtensions to Transformers, got an above error.
Then I fixed dupilicate of `$iterationArray` in `AmpProject/Validator/Spec/Section/Tags` and it is working well.

So, could you fix this problem?

**Comment by ediamin** [comment]
@saywo Thanks for reporting the issue. I can reproduce this error in PHP 5.6. Are you using the same version? I'll try to fix this issue ASAP.

**Comment by saywo** [comment]
@ediamin 
Yes, I'm using the same version(PHP5.6).
