### ISSUE TITLE
Uncaught `DomException` in `Document::moveInvalidHeadNodesToBody`

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-toolbox-php#522]
When trying to parse `https://chuseok.org/places-to-visit-during-chuseok-mid-autumn-summer/` with `Document::fromHtml()`, I get an uncaught `DomException`:

```
PHP Fatal error:  Uncaught DOMException: Not Found Error in /vendor/ampproject/amp-toolbox/src/Dom/Document.php:553
```

This is the offending code:

https://github.com/ampproject/amp-toolbox-php/blob/89cd1f6bad3512fb8a08aae5fb6aedc64e988392/src/Dom/Document.php#L655-L669

PHPStorm warns about accessing `$node` potentially causing a null pointer exception too.

This fixes the bug for me:

```dif
-while ($node) {
+while ($node !== null) {
```

**Comment by swissspidy** [comment]
Oh, I forgot that in our code base we remove everything after the closing `</head>` before parsing, for performance reasons (we don't need the body).

Basically:

```php
$html = $response->getBody();
$html_head_end = stripos( $html, '</head>' );
if ( $html_head_end ) {
$html = substr( $html, 0, $html_head_end );
}
````

So I guess that explains it. There's no body.

**Comment by ediamin** [comment]
@swissspidy In your html, the closing head tag is missing. I guess you can avoid the error by including the closing head tag. Despite of that, I've sent a PR to handle this kind of scenario. I hope it'll fix your error.
