### ISSUE TITLE
replaceMustacheTemplateTokens: Unterminated entity reference when the mustache template contains special character

### ISSUE THREAD

**Issue by buihoanghai** [ampproject/amp-toolbox-php#53]
I try to apply amp-toolbox for our website then facing this issue
![image](https://user-images.githubusercontent.com/6602376/105868406-bb2a4500-6028-11eb-9623-2b7a0c3eb29b.png)

The mustache templace contains "&" character in the href
![image](https://user-images.githubusercontent.com/6602376/105869337-b4e89880-6029-11eb-9c97-d87ab1fcd192.png)

**Comment by westonruter** [comment]
If you replace `&` with `&amp;` in your source code, does that prevent the error from happening?

Technically `&` alone is not valid markup, although all browsers support it and automatically parse it as `&amp;`.

**Comment by westonruter** [comment]
I can reproduce the issue with this markup:

```html
<template type="amp-mustache">
    <a href="https://example.com/?foo={{foo}}&bar={{bar}}&amp;baz={{baz}}">Link</a>
</template>
```

**Comment by schlessera** [comment]
It looks like this is a known bug in PHP which will not be fixed because of BC: https://bugs.php.net/bug.php?id=31191
