### ISSUE TITLE
Create CLI wrapper to run the optimizer from the shell

### ISSUE THREAD

**Issue by schlessera** [ampproject/amp-toolbox-php#82]
The library should come with a small lightweight CLI command wrapper so that you can run it from a shell or from within a CI environment easily.

Synopsis:
```bash
bin/optimize [input-file]
```

Examples:
```bash
# Run the optimizer on a specific file and store that file.
bin/optimize my-page.html > my-optimized-page.html
```
```bash
# Use STDIN if [input-file] is omitted
echo '<amp-img width=200 height=100 src="my-img.jpg">' | bin/optimize > optimized-amp-img.html
```

**Comment by westonruter** [comment]
This can mirror what the Node.js CLI tool offers: 

* https://github.com/ampproject/amp-toolbox/tree/main/packages/cli#optimize
* https://github.com/ampproject/amp-toolbox/blob/main/packages/cli/lib/cmds/optimize.js

Transformers could be specified via CLI args as well.
