### ISSUE TITLE
Add amp-bind optimizer

### ISSUE THREAD

**Issue by westonruter** [ampproject/amp-toolbox-php#84]
Per https://github.com/ampproject/amp-toolbox/pull/1147:

> See https://github.com/ampproject/amphtml/pull/32851
> 
> Part of https://github.com/ampproject/amphtml/issues/27590

----

> Enables a considerably faster scanning method in `amp-bind`, by injecting a `i-amphtml-binding` attribute on all elements with a bound attribute.

**Comment by sebastianbenz** [comment]
This is now live in runtime and validator.

**Comment by westonruter** [comment]
Good. Should be something we can include in AMP plugin v2.1 then!

**Comment by schlessera** [comment]
@sebastianbenz Will it be enabled by default now on the NodeJS optimizer, or does it stay disabled by default for now?

**Comment by sebastianbenz** [comment]
@schlessera this will be enabled by default.
