### ISSUE TITLE
, insteed of . in i-amphtml-sizer style

### ISSUE THREAD

**Issue by Lovntola** [ampproject/amp-toolbox-php#89]
**Is-state**
On some sites of my website the placeholder shows:
`<i-amphtml-sizer style="display:block;padding-top:20,4082%" slot="i-amphtml-svc"></i-amphtml-sizer>`

**Tobe-state**
`<i-amphtml-sizer style="display:block;padding-top:20.4082%" slot="i-amphtml-svc"></i-amphtml-sizer>`

**Rationale:**
In Chrome the image will not rendered. The Console shows a error of the format and ignores the CSS rule. The high is set to 0.

**Maybe:**
The only different between site with comma instead of dot that I can find ist the header:
`<html amp lang="nl" i-amphtml-layout="" i-amphtml-no-boilerplate="" transformed="self;v=1">` <--- with comma
`<html amp lang="de" i-amphtml-layout="" i-amphtml-no-boilerplate="" transformed="self;v=1">` <--- with dot

**Comment by schlessera** [comment]
This should be solved already via https://github.com/ampproject/amp-toolbox-php/pull/38.

@Lovntola Can you please test with latest `main` branch?

**Comment by Lovntola** [comment]
Yes this works,
Thank you
